#include <Adafruit_GFX.h>
#include <Adafruit_SSD1306.h>

//------------------------------------------------------------------------------
// File generated by LCD Assistant
// http://en.radzio.dxp.pl/bitmap_converter/
//------------------------------------------------------------------------------

// 한글 비트맵 (8 pixels per byte)
//static const unsigned char PROGMEM bitmap1 [] = {

//};


// 소프트웨어 4 SPI 사용
#define OLED_MOSI  2    // D1
#define OLED_CLK   3   // D0
#define OLED_DC    4
#define OLED_CS    7
#define OLED_RESET 9

// OLED 디스플레이 선언
Adafruit_SSD1306 display(OLED_MOSI, OLED_CLK, OLED_DC, OLED_RESET, OLED_CS);

void setup()   {
  // OLED 초기화                
  display.begin(SSD1306_SWITCHCAPVCC);
  display.setTextColor(WHITE);
  display.setTextSize(1);
  
  // 저전력을 위해 OLED 밝기 조정
  display.ssd1306_command(SSD1306_SETCONTRAST);
  display.ssd1306_command(0);
}

String test = "AAAAA";

void loop()
{
  display.clearDisplay();
  display.setTextSize(2);             // Normal 1:1 pixel scale
  display.setTextColor(SSD1306_WHITE);        // Draw white text
  display.setCursor(0,0);             // Start at top-left corner
  display.print(F("SMART IOT HOME"));
  display.println(test);

  display.display();
  delay(2000);
}
